version: "3.5"

services:
  speedchecker:
    container_name: speedchecker-container
    build:
      context: build-python/.
    image: speedchecker-image:0.10
    restart: unless-stopped

  database:
    container_name: sqlite3-database
    build:
      context: build-sql/.
    image: sqlite3-image:0.1
    restart: unless-stopped
