version: "3.5"

services:
  speedchecker:
    container_name: speedchecker-container
    build:
      context: build/.
    image: speedchecker-image:0.10
    restart: unless-stopped
    
  database:
    container_name: mysql-database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: securityisourwatchword
